---
# file: step_ca/tasks/main.yml

- name: Get ca installation information
  when: tinyca.step_ca_version == 'latest'
  check_mode: no
  block:
    - name: Get latest step-ca release information
      ansible.builtin.uri:
        url: https://api.github.com/repos/smallstep/certificates/releases/latest
        body_format: json
        return_content: yes
      register: step_ca_latest_release
      delegate_to: localhost
      become: no
      run_once: yes
      retries: 3
      delay: 5
    - name: Set latest release version
      ansible.builtin.set_fact:
        step_ca_version: "{{ (step_ca_latest_release.json.tag_name)[1:] }}"

- name: Load encrypted credentials
  community.sops.load_vars:
    file: ../inventories/general_vault.yaml
    expressions: ignore  # explicitly do not evaluate expressions
                          # on load (this is the default)
- name: Include Install playbook
  ansible.builtin.include_tasks: "install.yml"

- name: Include Init playbook
  ansible.builtin.include_tasks: "init.yml"

- name: Include run playbook
  ansible.builtin.include_tasks: "run.yml"