apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - namespace.yaml
patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-rbac-cm.yaml