vault:
    powerdns:
        domains:
            - ENC[AES256_GCM,data:5fUM7foPQ7LGPPc=,iv:4zmoI7qo1CTRpm8AkPQ5K3RosCyb1Czx2JaIUy/c3jw=,tag:AQ2twfklTLeLRQCr13BmCQ==,type:str]
        dyndns:
            tsig_key: ENC[AES256_GCM,data:XOfILoKZo3z64xI00r7+XrrDTRSyS8944YXAKsDjnO/veBifV3QOqeU3wDc2GMPyVlt+w1eRCQGxiQHkGVfM0yiVbLhOy/mgwSq3Cfcp0kFHY9WHkCgHaA==,iv:ddDPVRMfrp+aa+YUOa5igAn/i3HfKXsnTtERpc7kC0I=,tag:ajqdljhl7GUmZoQOvUAtBg==,type:str]
            tsig_schema: ENC[AES256_GCM,data:3jJY8lrDQV6Dha4=,iv:VMzPQz3dsxjJfL6M4+HG9B8rMucNgHsJd/wce213zi0=,tag:QRmfX4IkViotLWqDM0ky1Q==,type:str]
            tsig_name: ENC[AES256_GCM,data:leqrNFnw+6g=,iv:RTt2slPE1G/8SaZE6Qdy15J0U5cajU+j5GR3ubMX3bE=,tag:+B31YWpEGm7XODSSHlIgjQ==,type:str]
            domain: ENC[AES256_GCM,data:z6piL6nTTS+P2L8=,iv:pue92AVbtwtIV9TwDk3vlHOfg8ZgzW5FkErzd1xJcPI=,tag:k65pLB6gEISFerASfY8/vw==,type:str]
            allow_updates_from:
                - ENC[AES256_GCM,data:HoZ4YEUANDq60RUoAvm5nA==,iv:CStb9DdWLmhYv0/rok+Chqm9MHo8BBGExeLyUSPMGhQ=,tag:Kh9EEOWzLVY1tIXBrlruIg==,type:str]
                - ENC[AES256_GCM,data:RZod5LFpHmPgo2NmxZEpLQ==,iv:hWT0Z/6RINiLD5la+r5UikxK2nIsvX1OjI2h3vFPjB0=,tag:h9NYWt0UvYX6HCGb6DFnCg==,type:str]
                - ENC[AES256_GCM,data:gVGNEvdZdpyGYPzTjBk5mQ==,iv:NKVW8MLgdxPMruPfRG6hQVaYZanqNP6jGiUc6JQ0+eA=,tag:UwvL4k1+1tZkfgznvEKxcw==,type:str]
                - ENC[AES256_GCM,data:XJm3jsbrrfjXVZq0dDtrWUjA8KtSFm+SPIoKKYgZNVFf44uNvNqU,iv:aW5f4yIWg52NdNXB/h6GWprVONPwohSiOI7nSmzYyos=,tag:JfbwwrS8V6V18V+0jbe0ow==,type:str]
        webfrontend:
            hostname: ENC[AES256_GCM,data:YvslvKYnK16DwF8YZ5j+,iv:YFgTVHABU/UTeS2cQ3LxjjBEc2vK2KPDu0bhoQ6TIlU=,tag:Bm5VfOEonu7esgtqSk0TCQ==,type:str]
            api_password: ENC[AES256_GCM,data:ENZsZjmB8lu0GigkxFVQndCmkg8c,iv:VGbp2cguio2R9XuGmcOdSmKgZJkNtvq6Ra5/tRa3t6M=,tag:5BN5s1sEl970JgMGG+wDmw==,type:str]
    tinyca:
        name: ENC[AES256_GCM,data:3tv0+NJFvLiS,iv:UN3GcbhOfTXLbIDRyETlNycIrDTq/zXt0oellQsjJwM=,tag:/2+b1Q0blRB+fyTmItxopw==,type:str]
        init_password: ENC[AES256_GCM,data:4Ov4Yd04LbIiR64K+WR9IE6LEE9I9tHGcOyh36DT,iv:CT/X3On3tlcqyAhhrQ7YppryFraVkXO5IWClvWNbgH0=,tag:TDUpTgwb9yCjoFggrE1RNA==,type:str]
        provisioner_admin: ENC[AES256_GCM,data:+wyz81ccCDx61qGk29j62A==,iv:VdT9h0UzERutFhomjU9N0B1mfi9H1mt3G+bGny78HA8=,tag:UwFtHlR2FWidsvPUfP4azg==,type:str]
        provisioner_password: ENC[AES256_GCM,data:zQM/UwNULK7sw2Gxe6pzOWM8Je1ncrLtUOGko0LK,iv:w8V+DjSiLUBKcx541W3IT1wGWGLApHMzg8DvPrlgulA=,tag:aDY+1FeDYv1SoltVITtvnQ==,type:str]
        yubi_piv_pin: ENC[AES256_GCM,data:/Q5DfH4WGYk=,iv:Zjql3ZCrlcamssShDDjxMdoW2+APRPUbNzI3aD0jLMg=,tag:KUp+xF/6ccSGFlwQ2RkwHA==,type:int]
        yubi_piv_mgmt_key: ENC[AES256_GCM,data:9UEM0wMnQxsfasdKdg/tLMCVpc9JqURI1h1AY2e/pvl+Orzq0CkuLFvqqX8Lefjc,iv:oKQGwwpuoVimRvjLYGHwYs/w3wXGW6guHDAiWaiIJdo=,tag:igdFy5HvUXcc1bojtN7sfw==,type:str]
        key_type: ENC[AES256_GCM,data:wk0=,iv:4MfINyYidfe3Ad82k1GT/cT5h2wmkCcXTjs0JZmm5aE=,tag:TzAg9Gi3y2JbWEyWbKV/rQ==,type:str]
        key_curve: ENC[AES256_GCM,data:FhWAGg==,iv:xXvRnyO5lX2l4vTq4u0d0R3QeY61EOVJZ1pR7RwwSlU=,tag:mL0v+4ymK6F0c0vjKz6tqA==,type:str]
        key_size: null
        key_hash: ENC[AES256_GCM,data:jdI4Xthn,iv:lx9dy7byzDQb550VF3Yqj+gPG+HuiL/fyVQWh7hHmfk=,tag:ux/1fAvGX/WOEmrkWGla8A==,type:str]
        address: ENC[AES256_GCM,data:kqO5ww==,iv:R8wvr39Mn328BbnMi3wFiFgSzFBw1egu/NsuGFSb4iE=,tag:u5/Mal76WTUOOzyitNJUkg==,type:str]
        dns_domain:
            - ENC[AES256_GCM,data:VYOFOVPX0U+jH3HVuK8=,iv:UWEiqn+5vNxMRWy87adYidZ2+Q6PBBeTrJalvWiE968=,tag:eqkDsKNe1zWmlWnaZL/iCw==,type:str]
            - ENC[AES256_GCM,data:RSCG93uIICgg5XgGUu6z,iv:jnzlmW03SgkRHAZnPOhSdD8cIE9F9qn1bvd8DUZkRFE=,tag:3JuRu8BRZaOV85ZvHha2bA==,type:str]
            - ENC[AES256_GCM,data:qK3ypgcTCAJHKFdzj4D58htP6sX1DSc7F6irrCr345C7U3HnAA==,iv:oI8+a8aLWl7ceWgdvJNsneP9eeSC92kfy5neqPCttXw=,tag:UCtoHCTm/u95OTisVS1nIQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:PcPqYMKxb6h+5FyP,iv:6nq2/r1GbsDubNxnjj5Qp48HrJTH0KQC3vOGlJxuubw=,tag:aTx/hZHtQomB/qS1LOgBPg==,type:str]
    docker_hub_username: ENC[AES256_GCM,data:geRqa+2C,iv:8tcQjFYz4trNXiZR7RO6xRZ6ue0hTaOn1GiXAkz49Jo=,tag:2ELjiE7gEbAcGv/ASi7G6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tqvmkray65fy4re6fx8l5kq9cjl0uf3yjfd60wn882yrqp2stp6s3x6vgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeGF0aVpJYVEvdktZdzl0
            bFBKMGg5dEJ6SVA1ODBZOVpJZHNRbWFPdW00CjV5bDcwRDlLUzhaS2tOUGRDVXZZ
            bVlEc2c0S0Yzd0JyZGFqbnQyK3Q5MkUKLS0tIDY3aWZEQjhnYWdhMU9ZVUJSYlB3
            SGhxUFI1MDVNb0lxa2FMNVRQMFRQckkKWMJ+zmUlhznLGzFVRDRcDpXfiuPM6ium
            TPCiG547qsafg0YBYRgWM23bEFcd7RaUK7a/6tIn6kltnxNOGoTe5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-11T11:22:44Z"
    mac: ENC[AES256_GCM,data:EPsBWG7hDNYhU5ZAF01HL1Mlz2WWGOOPov6nYjmUfgEiyhO0jllpC5IGredbyPKTGi7xwvPSvLqFv0mGw4y+izaqbRnOqoKolZ7Jqcbw8MgcKIGPABKRc2ipvatV6GCxyeIwWiTX0YHVNOckJYvyMUYlv1YnOx/s/CWxJTYVdRU=,iv:4pI0KxDVy4i13xSDEt4QSLGsjOPgqw2iWdwCz6o7Y+w=,tag:ShUTLkbUE+mQkmFnDe+k7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
