---
# file: pdns.yaml
- name: Install powerdns core service
  hosts: dns_servers
  tags:
    - dns
    - core
  tasks:
    # Load sops encrypted vault variables
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: ../inventories/general_vault.yaml
        expressions: ignore  # explicitly do not evaluate expressions
                              # on load (this is the default)
  roles:
    - role: powerdns
      become: true
