---
# file: playbooks/tinyca.yml
- name: Install tinyca core service on raspi
  hosts: ca_servers
  tags:
    - tinyca
    - core
  become: true
  tasks:
    # Load sops encrypted vault variables
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: ../inventories/general_vault.yaml
        expressions: ignore  # explicitly do not evaluate expressions
                              # on load (this is the default)
  roles:
    - role: noise_generator  # noqa syntax-check[specific] 
    - role: core/step_ca # noqa syntax-check[specific]