test: ENC[AES256_GCM,data:ysHMew==,iv:y2EoJ8FoTfP/0U2noBO4w37PLFtH7agiZ/IaPY+ch+0=,tag:ruE84imIErd6cpH2BpYxgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rn0tdttk6ylrven8jj5rph3nvmarhf6cjywupzdva52rdxs82p3slee9xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdUFuQ2ZtTmg0cUgxcjJJ
            ZWZBa0FWbTY1M1d4M3NOS0dvTXRIbmtTdlRvCkpFL3IxZFdwUm9hNENLYzFjMkJY
            MzlBMXVFd2tad25nUEhiK2JwTFpIdU0KLS0tIGhSTDJuU21KNnczeEM2cTVWVHJW
            V202TlZRWVFpMngwbnRzWXFmUkd3Wk0KO8GPvafd4m/cJJ89axrmIej28P+O63Qz
            o2zs0bMepWuE8BNka/HFxwkMkJQqmtiD29yis+B0TvhoPnTSbCn90Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T14:40:25Z"
    mac: ENC[AES256_GCM,data:y6nyF3pp45vCw4z1X05eSQYDryUCfSrmD5cVLxAVM1kCzbEHs3QYFoS6odQ9tSNyrPdvCBuQmrA4NWn+oRXcaT/fRVNYHAmoxLn3l6PTNYg8+W10U6VTR/0DkBEg6wH4i28sOESRXefg8izHEE96uVuuZKJw0Q8GWRNbu5uaeZ0=,iv:Qvu7IR4ZeECJXFyIKzipCzpx23osLzZj3j7Mq0kKoKs=,tag:ljwBQYpSuuTxNvAr7wPLag==,type:str] # noqa 204
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
