cloudflare_api_token: ENC[AES256_GCM,data:a2++j+aCqHKaNbiXlw6DLZdziVfQAsHQIjEqk5B/KhIQJmSqZDCQ/A==,iv:9AGH3bly2jXsEK5gCqruys7sbqCzw01EU69hvQDhmuU=,tag:HXSEyVlwX6Ya3DEVF27PAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tqvmkray65fy4re6fx8l5kq9cjl0uf3yjfd60wn882yrqp2stp6s3x6vgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxall5QUxHekhBWlorSmpj
            MkxNZ3duQkRqOE82SDJNWUJ4TU5Qd01PY0JnCmhER1VxM2JNdG5KR3JxdXA1dU5r
            SGZGS0FIYjFGbitkYU9qeVV0UlFpNzAKLS0tIEx3Vlo5TmsrdllWUzIxemRzcmR1
            WThRSjlrUG8vSDM0S0Y2b1pUdlBNYjQK2tUL91r9j+/WkpbJm38AXiiYCQ4JQHaQ
            u/MTrRuyU/aj+S3Q0QwdpZl7a1a665mPxgHGMujp+pdRrcRQRbK9HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-14T20:51:39Z"
    mac: ENC[AES256_GCM,data:6j+i5lAefmpBVijoLuJCFmH3cNAoG6L6dp2uInGHgZzWNeyXcbAJOgoC8K0yhiXWnJCr+tHfFfbPA2A5oBe2lWEJZO10EcvEoecH9Uaeg9i4qN6hKHCgUJd3ay5+dFjbabDQjUoB5s4koxetq/axfV45WEgiJTWjmkRvID4yn8o=,iv:4Jxl2uB7MmjJtvU9Aou5PIbw4WoFsExFtyTcv5yzEao=,tag:WOijVvZ6umpq2XMBYQ0gKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
