---
- name: Make sure timesyncd is configured
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and Start timedatectl service
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true